apiVersion: v1
kind: Service
metadata:
  name: fiddle-run
spec:
  selector:
    app: fiddle-run
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiddle-run
spec:
  selector:
    matchLabels:
      app: fiddle-run
  template:
    metadata:
      labels:
        app: fiddle-run
    spec:
      imagePullSecrets:
      - name: quillreg-secret
      containers:
      - name: fiddle-run
        image: quillreg.azurecr.io/fiddle-run:cfa
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
  name: fiddle-run-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - tools.quill.codes
    - www.quill.codes
    secretName: letsencrypt-prod
  rules:
  - host: tools.quill.codes
    http:
      paths:
      - backend:
          serviceName: fiddle-run
          servicePort: 80
  - host: www.quill.codes
    http:
      paths:
      - backend: 
          serviceName: fiddle-run
          servicePort: 80